/**
 * Vetting Audit Log Helpers
 * ═════════════════════════
 *
 * Parsers for the system-generated note content that the backend emits
 * when an admin changes an applicant's vetting status. These notes get
 * stored in the `notes` list alongside free-form admin notes, and the
 * UI needs to distinguish "this note is a system-logged status change"
 * from "this note is a human-written review comment" so it can render
 * the former with a status badge.
 *
 * SCOPE — why this is in its own file
 * -----------------------------------
 * This is NOT display configuration (colors, labels, icons — those
 * live in constants/vettingStatusConfig.ts). This is audit log parsing:
 * taking a free-text note content string and figuring out whether it
 * was auto-generated by the backend and which vetting status it
 * represents. The two concerns are deliberately kept separate.
 *
 * If the backend changes the exact text of its system-generated notes
 * (see `GetSimplifiedActionDescription()` in the backend), update the
 * NOTE_PREFIX_TO_STATUS map below in lockstep.
 *
 * SINGLE SOURCE OF TRUTH
 * ----------------------
 * Before this file existed, two separate components maintained their
 * own copies of the note-text → status mapping:
 *   - apps/web/src/features/admin/vetting/components/VettingNoteRenderer.tsx
 *   - apps/web/src/components/notes/MemberNoteRenderer.tsx
 *
 * The two copies were slightly different: one used exact-match lookup,
 * the other used startsWith() to accommodate admin reasons appended
 * after "\n\nReason: ...". This file unifies both into a single
 * prefix-based matcher that handles both cases, and exports helpers
 * that the two renderers (or any future caller) can import.
 */

import type { VettingStatus } from '../constants/vettingStatusConfig';

/**
 * Result returned by both detection helpers.
 *
 * `isSystem` is true when the note content matches a known backend
 * auto-generated prefix. `status` is the canonical VettingStatus string
 * the note represents, or undefined for free-form / unrecognized notes.
 */
export interface SystemNoteDetection {
  isSystem: boolean;
  status?: VettingStatus;
}

/**
 * Mapping from the backend's system-generated note prefix to the
 * canonical VettingStatus the note represents.
 *
 * Order matters for startsWith matching: more-specific prefixes should
 * come first. Today none of these overlap, but if "Application approved"
 * and "Application approved and welcomed" were both valid, the longer
 * prefix would need to be listed first.
 *
 * These prefixes mirror `GetSimplifiedActionDescription()` on the
 * backend. If the backend changes any of these strings, update this
 * map in lockstep or audit badges will silently stop rendering.
 */
const NOTE_PREFIX_TO_STATUS: ReadonlyArray<{
  prefix: string;
  status: VettingStatus;
}> = [
  { prefix: 'Application submitted', status: 'UnderReview' },
  { prefix: 'Approved for interview', status: 'InterviewApproved' },
  { prefix: 'Interview completed', status: 'FinalReview' },
  { prefix: 'Application approved', status: 'Approved' },
  { prefix: 'Application denied', status: 'Denied' },
  { prefix: 'Application placed on hold', status: 'OnHold' },
  { prefix: 'Returned to review', status: 'UnderReview' },
  { prefix: 'Application withdrawn', status: 'Withdrawn' },
];

/**
 * Detect whether a note content string is a system-generated status
 * change, and if so return which VettingStatus it represents.
 *
 * Uses prefix matching (not exact match) so notes with admin reasons
 * appended after "\n\nReason: ..." are still recognized. This is the
 * behavior the MemberNoteRenderer needed; the VettingNoteRenderer
 * previously used exact matching but prefix matching is a strict
 * superset so callers can use this helper uniformly.
 *
 * @param noteText The free-text content of the note
 * @returns `{ isSystem, status }` — isSystem true if the note starts
 *          with a known prefix, with `status` set to the corresponding
 *          VettingStatus. Otherwise `{ isSystem: false }`.
 */
export function detectSystemGeneratedNote(
  noteText: string | null | undefined
): SystemNoteDetection {
  if (!noteText) return { isSystem: false };

  for (const { prefix, status } of NOTE_PREFIX_TO_STATUS) {
    if (noteText.startsWith(prefix)) {
      return { isSystem: true, status };
    }
  }

  return { isSystem: false };
}
