-- Add missing ASP.NET Core Identity columns to Users table in public schema
ALTER TABLE public."Users" 
ADD COLUMN IF NOT EXISTS "UserName" character varying(256),
ADD COLUMN IF NOT EXISTS "NormalizedUserName" character varying(256),
ADD COLUMN IF NOT EXISTS "NormalizedEmail" character varying(256),
ADD COLUMN IF NOT EXISTS "EmailConfirmed" boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "PasswordHash" text,
ADD COLUMN IF NOT EXISTS "SecurityStamp" text,
ADD COLUMN IF NOT EXISTS "ConcurrencyStamp" text,
ADD COLUMN IF NOT EXISTS "PhoneNumber" text,
ADD COLUMN IF NOT EXISTS "PhoneNumberConfirmed" boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "TwoFactorEnabled" boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "LockoutEnd" timestamp with time zone,
ADD COLUMN IF NOT EXISTS "LockoutEnabled" boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "AccessFailedCount" integer NOT NULL DEFAULT 0;

-- Add indexes for Identity columns
CREATE INDEX IF NOT EXISTS "IX_Users_NormalizedUserName" ON public."Users" ("NormalizedUserName");
CREATE INDEX IF NOT EXISTS "IX_Users_NormalizedEmail" ON public."Users" ("NormalizedEmail");

-- Create other Identity tables if they don't exist
CREATE TABLE IF NOT EXISTS public."Roles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."UserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."UserClaims" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public."RoleClaims" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."Roles" ("Id") ON DELETE CASCADE
);

-- Create indexes for Identity tables
CREATE INDEX IF NOT EXISTS "IX_Roles_NormalizedName" ON public."Roles" ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_UserRoles_RoleId" ON public."UserRoles" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_UserClaims_UserId" ON public."UserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_UserLogins_UserId" ON public."UserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_RoleClaims_RoleId" ON public."RoleClaims" ("RoleId");