/**
 * Check-In System E2E Tests - Token Validation
 *
 * Tests session token authentication and validation for the kiosk mode check-in interface.
 * The check-in system NO LONGER uses user authentication (CheckInStaff role removed).
 * Instead, it uses session tokens generated by Administrators/EventOrganizers.
 *
 * Token Authentication Flow:
 * 1. Admin generates session token via API endpoint
 * 2. Token is embedded in check-in URL: /events/{eventId}/checkin?token={token}&event={eventId}
 * 3. Token sent in X-CheckIn-Token header for API calls
 * 4. NO user authentication required for check-in operations
 *
 * Test Scenarios:
 * - Valid token grants access to check-in interface
 * - Invalid/fake token shows error message
 * - Missing token shows error message
 * - Token for wrong event returns 403 Forbidden
 * - Revoked token cannot be used (401 Unauthorized)
 * - No authentication required with valid token
 * - Expired token shows error message
 *
 * API Endpoints:
 * - POST /api/checkin/session-tokens/generate (requires admin auth)
 * - POST /api/checkin/session-tokens/revoke (requires admin auth)
 * - GET /api/checkin/events/{eventId}/attendees (requires X-CheckIn-Token header)
 */

import { test, expect, Page, Browser } from '@playwright/test';
import {
  loginAsAdmin,
  generateSessionToken,
  revokeSessionToken,
  getTestEventId,
  navigateToCheckIn,
  getAttendees
} from './checkin/helpers/tokenHelpers';

test.describe('Check-In Token Validation', () => {
  let testEventId: string;

  test.beforeAll(async ({ browser }) => {
    // Get test event ID (no auth required for public events endpoint)
    const context = await browser.newContext();
    const page = await context.newPage();
    testEventId = await getTestEventId(page);
    await context.close();
  });

  test('Valid token allows access to check-in interface', async ({ browser }) => {
    // Step 1: Generate token as admin (separate context)
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();

    await loginAsAdmin(adminPage);
    const sessionToken = await generateSessionToken(adminPage, testEventId);

    await adminContext.close();

    // Step 2: Access check-in interface without authentication (kiosk mode)
    const kioskContext = await browser.newContext();
    const kioskPage = await kioskContext.newPage();

    // Clear cookies to ensure no user authentication
    await kioskPage.context().clearCookies();

    // Navigate to check-in with token
    await navigateToCheckIn(kioskPage, testEventId, sessionToken);

    // Step 3: Verify interface loads successfully
    await expect(kioskPage).not.toHaveURL(/unauthorized/);
    await expect(kioskPage).not.toHaveURL(/login/);

    // Verify check-in interface elements are visible
    const checkInHeading = kioskPage.locator('text=/check.?in/i').first();
    await expect(checkInHeading).toBeVisible({ timeout: 10000 });

    // Verify we're on the correct page (not redirected)
    const currentUrl = kioskPage.url();
    expect(currentUrl).toContain(`/events/${testEventId}/checkin`);

    // Verify NO user profile or auth UI elements visible (kiosk mode)
    const userProfile = kioskPage.locator('[data-testid="user-profile"], text=/logged in as/i');
    await expect(userProfile).not.toBeVisible();

    await kioskContext.close();
  });

  test('Invalid token shows error message', async ({ page }) => {
    // Clear cookies (no user auth)
    await page.context().clearCookies();

    // Navigate with fake/invalid token
    const fakeToken = 'invalid-token-12345';
    await page.goto(`http://localhost:5173/events/${testEventId}/checkin?token=${fakeToken}&event=${testEventId}`);
    await page.waitForLoadState('networkidle');

    // Verify error message displayed
    const errorMessage = page.locator('[role="alert"], .error, .notification').filter({ hasText: /invalid.*token|token.*invalid|access denied/i });
    await expect(errorMessage).toBeVisible({ timeout: 10000 });

    // Verify check-in interface NOT accessible
    const addWalkInButton = page.locator('button').filter({ hasText: /add walk.?in/i });
    await expect(addWalkInButton).not.toBeVisible();
  });

  test('Missing token shows error message', async ({ page }) => {
    // Clear cookies
    await page.context().clearCookies();

    // Navigate to check-in URL without token parameter
    await page.goto(`http://localhost:5173/events/${testEventId}/checkin`);
    await page.waitForLoadState('networkidle');

    // Verify "Invalid Check-In Link" or similar error
    const errorMessage = page.locator('[role="alert"], .error, .notification').filter({ hasText: /invalid.*link|missing.*token|access denied/i });
    await expect(errorMessage).toBeVisible({ timeout: 10000 });

    // Verify check-in functionality NOT available
    const checkInButton = page.locator('button').filter({ hasText: /check.?in/i });
    await expect(checkInButton).not.toBeVisible();
  });

  test('Token for wrong event returns 403', async ({ browser }) => {
    // Generate token for event A
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();

    await loginAsAdmin(adminPage);
    const sessionToken = await generateSessionToken(adminPage, testEventId);

    // Get a different event ID (if available) or use fake ID
    const fakeEventId = 'fake-event-id-12345';

    await adminContext.close();

    // Try to use event A token for event B
    const kioskContext = await browser.newContext();
    const kioskPage = await kioskContext.newPage();

    await kioskPage.context().clearCookies();

    // Try to get attendees for wrong event
    const attendeesData = await kioskPage.request.get(
      `http://localhost:5655/api/checkin/events/${fakeEventId}/attendees`,
      {
        headers: {
          'X-CheckIn-Token': sessionToken
        }
      }
    );

    // Verify 403 Forbidden error (token is for different event)
    expect(attendeesData.status()).toBe(403);

    await kioskContext.close();
  });

  test('Revoked token cannot be used', async ({ browser }) => {
    // Step 1: Generate token
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();

    await loginAsAdmin(adminPage);
    const sessionToken = await generateSessionToken(adminPage, testEventId);

    // Step 2: Revoke token
    await revokeSessionToken(adminPage, sessionToken);

    await adminContext.close();

    // Step 3: Try to access check-in with revoked token
    const kioskContext = await browser.newContext();
    const kioskPage = await kioskContext.newPage();

    await kioskPage.context().clearCookies();

    await kioskPage.goto(`http://localhost:5173/events/${testEventId}/checkin?token=${sessionToken}&event=${testEventId}`);
    await kioskPage.waitForLoadState('networkidle');

    // Verify error message for revoked token
    const errorMessage = kioskPage.locator('[role="alert"], .error').filter({ hasText: /revoked|invalid.*token|access denied/i });
    await expect(errorMessage).toBeVisible({ timeout: 10000 });

    // Verify API calls with revoked token fail
    const attendeesResponse = await kioskPage.request.get(
      `http://localhost:5655/api/checkin/events/${testEventId}/attendees`,
      {
        headers: {
          'X-CheckIn-Token': sessionToken
        }
      }
    );

    // Verify 401 Unauthorized (token revoked)
    expect(attendeesResponse.status()).toBe(401);

    await kioskContext.close();
  });

  test('No authentication required for valid token', async ({ browser }) => {
    // Step 1: Generate token
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();

    await loginAsAdmin(adminPage);
    const sessionToken = await generateSessionToken(adminPage, testEventId);

    await adminContext.close();

    // Step 2: Create completely unauthenticated browser context
    const kioskContext = await browser.newContext();
    const kioskPage = await kioskContext.newPage();

    // Clear all cookies and storage
    await kioskPage.context().clearCookies();

    // Navigate with token
    await navigateToCheckIn(kioskPage, testEventId, sessionToken);

    // Step 3: Verify full check-in functionality available
    const checkInHeading = kioskPage.locator('text=/check.?in/i').first();
    await expect(checkInHeading).toBeVisible({ timeout: 10000 });

    // Verify add walk-in button available (check-in functionality works)
    const addWalkInButton = kioskPage.locator('button').filter({ hasText: /add walk.?in/i });
    await expect(addWalkInButton).toBeVisible({ timeout: 10000 });

    // Step 4: Verify NO user profile/auth UI elements visible
    const userProfileMenu = kioskPage.locator('[data-testid="user-menu"], [data-testid="user-profile"]');
    await expect(userProfileMenu).not.toBeVisible();

    const logoutButton = kioskPage.locator('button').filter({ hasText: /log.?out/i });
    await expect(logoutButton).not.toBeVisible();

    // Step 5: Verify API calls work with token (no auth cookie)
    const attendeesData = await getAttendees(kioskPage, testEventId, sessionToken);
    expect(attendeesData).toBeTruthy();

    await kioskContext.close();
  });

  test('Expired token shows error message', async ({ browser }) => {
    // Generate token with very short expiration (0.001 hours = 3.6 seconds)
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();

    await loginAsAdmin(adminPage);
    const sessionToken = await generateSessionToken(adminPage, testEventId, 0.001);

    await adminContext.close();

    // Wait for token to expire (4 seconds to be safe)
    await new Promise(resolve => setTimeout(resolve, 4000));

    // Try to access check-in with expired token
    const kioskContext = await browser.newContext();
    const kioskPage = await kioskContext.newPage();

    await kioskPage.context().clearCookies();

    await kioskPage.goto(`http://localhost:5173/events/${testEventId}/checkin?token=${sessionToken}&event=${testEventId}`);
    await kioskPage.waitForLoadState('networkidle');

    // Verify error message for expired token
    const errorMessage = kioskPage.locator('[role="alert"], .error').filter({ hasText: /expired|invalid.*token|access denied/i });
    await expect(errorMessage).toBeVisible({ timeout: 10000 });

    // Verify API calls with expired token fail
    const attendeesResponse = await kioskPage.request.get(
      `http://localhost:5655/api/checkin/events/${testEventId}/attendees`,
      {
        headers: {
          'X-CheckIn-Token': sessionToken
        }
      }
    );

    // Verify 401 Unauthorized (token expired)
    expect(attendeesResponse.status()).toBe(401);

    await kioskContext.close();
  });
});
