/**
 * Check-In System E2E Tests - Attendee Check-In Workflow
 *
 * Tests the core check-in functionality for pre-registered attendees using kiosk mode session tokens.
 * NO user authentication required - uses session tokens generated by Administrator.
 *
 * Verifies:
 * - Checking in a registered attendee
 * - Preventing duplicate check-ins
 * - Check-in modal displays correct attendee information
 * - Token validation during check-in operations
 *
 * Authentication:
 * - Uses session tokens (NO CheckInStaff login)
 * - Admin generates token in beforeAll
 * - Token sent in X-CheckIn-Token header for API calls
 * - Cookies cleared to simulate kiosk mode
 *
 * API Endpoints:
 * - POST /api/checkin/events/{eventId}/checkin (requires X-CheckIn-Token)
 * - GET /api/checkin/events/{eventId}/attendees (requires X-CheckIn-Token)
 *
 * Note: This test requires pre-registered attendees in the database.
 * If no attendees exist, some tests may be skipped gracefully.
 */

import { test, expect } from '@playwright/test';
import {
  loginAsAdmin,
  generateSessionToken,
  getTestEventId,
  navigateToCheckIn,
  getAttendees
} from './checkin/helpers/tokenHelpers';

// Environment-aware URLs for container/host compatibility
const WEB_BASE_URL = process.env.PLAYWRIGHT_BASE_URL || 'http://localhost:5173';
const API_BASE_URL = process.env.API_URL || 'http://localhost:5655';


// CHECK-IN KIOSK MODE TESTS - ATTENDEE WORKFLOW
// Routes: /events/:eventId/checkin
// Uses session tokens for access control - NO user login required
test.describe('Check-In Attendee Workflow', () => {
  let testEventId: string;
  let sessionToken: string;

  test.beforeAll(async ({ browser }) => {
    // Admin context for token generation
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();

    await loginAsAdmin(adminPage);
    testEventId = await getTestEventId(adminPage);

    await adminContext.close();
  });

  test.beforeEach(async ({ page, browser }) => {
    // Generate fresh token for each test with extended expiration (24 hours)
    // This prevents token expiration during test execution
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();
    await loginAsAdmin(adminPage);
    sessionToken = await generateSessionToken(adminPage, testEventId, 24); // 24 hours
    await adminContext.close();

    // NO login - clear cookies to simulate kiosk mode
    await page.context().clearCookies();

    // Navigate with fresh token
    await navigateToCheckIn(page, testEventId, sessionToken);
  });

  test('Check in a registered attendee', async ({ page }) => {
    // Get attendees from API using session token (NO auth cookie)
    const attendeesData = await getAttendees(page, testEventId, sessionToken);

    // Skip test if no attendees or all are checked in
    if (!attendeesData || !attendeesData.attendees || attendeesData.attendees.length === 0) {
      test.skip();
      return;
    }

    // Find an attendee who is NOT checked in
    const uncheckedAttendee = attendeesData.attendees.find(
      (a: any) => a.registrationStatus !== 'checked-in' && a.registrationStatus !== 'CheckedIn'
    );

    if (!uncheckedAttendee) {
      // All attendees are already checked in - create a test registration first
      test.skip();
      return;
    }

    // Find the attendee row by sceneName (UI displays sceneName, not email)
    const sceneName = uncheckedAttendee.sceneName || uncheckedAttendee.email;
    const attendeeRow = page.locator('tr').filter({ hasText: sceneName }).first();
    await expect(attendeeRow).toBeVisible({ timeout: 10000 });

    // Click "Covid Test" button first (initial state for unchecked attendees)
    // The workflow is: Covid Test → Check In → Checked In
    const covidTestButton = attendeeRow.locator('button').filter({ hasText: /covid test/i }).first();
    await expect(covidTestButton).toBeVisible({ timeout: 5000 });
    await covidTestButton.click();

    // Now "Check In" button appears
    const checkInButton = attendeeRow.locator('button').filter({ hasText: /check.?in/i }).first();
    await expect(checkInButton).toBeVisible({ timeout: 5000 });
    await checkInButton.click();

    // KIOSK MODE: Notifications are disabled for streamlined UX
    // Instead, verify the attendee shows as checked in (text changes to "✓ Checked In")
    const checkedInText = attendeeRow.locator('text=/Checked In/i').first();
    await expect(checkedInText).toBeVisible({ timeout: 5000 });
  });

  test('Cannot check in same attendee twice', async ({ page }) => {
    // Get attendees from API using session token
    const attendeesData = await getAttendees(page, testEventId, sessionToken);

    // Skip test if no checked-in attendees exist
    if (!attendeesData || !attendeesData.attendees || attendeesData.attendees.length === 0) {
      test.skip();
      return;
    }

    // Find an attendee who IS checked in
    const checkedInAttendee = attendeesData.attendees.find(
      (a: any) => a.registrationStatus === 'checked-in' || a.registrationStatus === 'CheckedIn'
    );

    if (!checkedInAttendee) {
      test.skip();
      return;
    }

    // Find the attendee row by sceneName (UI displays sceneName, not email)
    const sceneName = checkedInAttendee.sceneName || checkedInAttendee.email;
    const attendeeRow = page.locator('tr').filter({ hasText: sceneName }).first();
    await expect(attendeeRow).toBeVisible({ timeout: 10000 });

    // Verify attendee shows "Checked In" text (complete state shows "✓ Checked In")
    const checkedInText = attendeeRow.locator('text=/Checked In/i').first();
    await expect(checkedInText).toBeVisible({ timeout: 5000 });

    // Verify NO "Covid Test" or "Check In" buttons exist for this attendee (complete state shows text, not buttons)
    const covidTestButton = attendeeRow.locator('button').filter({ hasText: /covid test/i });
    await expect(covidTestButton).toHaveCount(0);

    const checkInButton = attendeeRow.locator('button').filter({ hasText: /^check.?in$/i });
    await expect(checkInButton).toHaveCount(0);
  });

  test('Two-step check-in workflow (Covid Test → Check In)', async ({ page }) => {
    // This test verifies the streamlined check-in workflow:
    // 1. Click "Covid Test" button (purple) - marks COVID test complete
    // 2. Click "Check In" button (green) - completes the check-in
    // No confirmation modal - direct button workflow for kiosk efficiency

    // Get attendees from API using session token
    const attendeesData = await getAttendees(page, testEventId, sessionToken);

    // Skip if no unchecked attendees
    if (!attendeesData || !attendeesData.attendees || attendeesData.attendees.length === 0) {
      test.skip();
      return;
    }

    const uncheckedAttendee = attendeesData.attendees.find(
      (a: any) => a.registrationStatus !== 'checked-in' && a.registrationStatus !== 'CheckedIn'
    );

    if (!uncheckedAttendee) {
      test.skip();
      return;
    }

    // Find attendee row by sceneName (UI displays sceneName, not email)
    const sceneName = uncheckedAttendee.sceneName || uncheckedAttendee.email;
    const attendeeRow = page.locator('tr').filter({ hasText: sceneName }).first();
    await expect(attendeeRow).toBeVisible({ timeout: 10000 });

    // Verify the attendee name is displayed correctly
    const nameDisplay = attendeeRow.locator(`text=${sceneName}`);
    await expect(nameDisplay).toBeVisible({ timeout: 3000 });

    // Step 1: Verify "Covid Test" button is visible (initial state)
    const covidTestButton = attendeeRow.locator('button').filter({ hasText: /covid test/i }).first();
    await expect(covidTestButton).toBeVisible({ timeout: 5000 });

    // Click "Covid Test" button
    await covidTestButton.click();

    // Step 2: Verify "Check In" button appears (intermediate state)
    const checkInButton = attendeeRow.locator('button').filter({ hasText: /check.?in/i }).first();
    await expect(checkInButton).toBeVisible({ timeout: 5000 });

    // Click "Check In" button to complete
    await checkInButton.click();

    // Verify final state: "Checked In" text appears (complete state)
    const checkedInText = attendeeRow.locator('text=/Checked In/i').first();
    await expect(checkedInText).toBeVisible({ timeout: 5000 });
  });

  test('Token validation fails for expired token during check-in', async ({ browser }) => {
    // Generate token with very short expiration
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();

    await loginAsAdmin(adminPage);
    const shortLivedToken = await generateSessionToken(adminPage, testEventId, 0.001); // 3.6 seconds

    await adminContext.close();

    // Wait for token to expire
    await new Promise(resolve => setTimeout(resolve, 4000));

    // Try to use expired token
    const kioskContext = await browser.newContext();
    const kioskPage = await kioskContext.newPage();

    await kioskPage.context().clearCookies();

    // Try to get attendees with expired token
    const response = await kioskPage.request.get(
      `${API_BASE_URL}/api/checkin/events/${testEventId}/attendees`,
      {
        headers: {
          'X-CheckIn-Token': shortLivedToken
        }
      }
    );

    // Verify 401 Unauthorized (token expired)
    expect(response.status()).toBe(401);

    await kioskContext.close();
  });
});
