/**
 * Check-In System E2E Tests - Attendee Check-In Workflow
 *
 * Tests the core check-in functionality for pre-registered attendees using kiosk mode session tokens.
 * NO user authentication required - uses session tokens generated by Administrator.
 *
 * Verifies:
 * - Checking in a registered attendee
 * - Preventing duplicate check-ins
 * - Check-in modal displays correct attendee information
 * - Token validation during check-in operations
 *
 * Authentication:
 * - Uses session tokens (NO CheckInStaff login)
 * - Admin generates token in beforeAll
 * - Token sent in X-CheckIn-Token header for API calls
 * - Cookies cleared to simulate kiosk mode
 *
 * API Endpoints:
 * - POST /api/checkin/events/{eventId}/checkin (requires X-CheckIn-Token)
 * - GET /api/checkin/events/{eventId}/attendees (requires X-CheckIn-Token)
 *
 * MIGRATION NOTE: Uses DataFactory for test data creation, but keeps token generation logic
 * as it's specific to check-in workflow and not general test data.
 */

import { expect } from '@playwright/test';
import { test } from '../lib/datafactory/fixtures/test.fixture';
import {
  loginAsAdmin,
  generateSessionToken,
  navigateToCheckIn,
  getAttendees
} from './checkin/helpers/tokenHelpers';

// CRITICAL: DO NOT use hardcoded WEB_BASE_URL or API_BASE_URL
// Use relative URLs and tokenHelpers (which use relative URLs) for container compatibility


// CHECK-IN KIOSK MODE TESTS - ATTENDEE WORKFLOW
// Routes: /events/:eventId/checkin
// Uses session tokens for access control - NO user login required
test.describe('Check-In Attendee Workflow', () => {
  let testEventId: string;
  let sessionToken: string;

  test('Check in a registered attendee', async ({ page, df, browser }) => {
    // Create test data using DataFactory
    const event = await df.events.createPublished(`Check-In Test ${Date.now()}`);

    const sessionStart = new Date();
    sessionStart.setHours(sessionStart.getHours() + 2);
    const sessionEnd = new Date(sessionStart.getTime() + 3 * 60 * 60 * 1000);

    const session = await df.sessions.create({
      eventId: event.id,
      title: 'Test Session',
      startTime: sessionStart,
      endTime: sessionEnd,
      maxCapacity: 20,
    });

    const ticketType = await df.ticketTypes.create({
      eventId: event.id,
      sessionId: session.id,
      name: 'General Admission',
      price: 0,
      quantityAvailable: 20,
    });

    // Create a user with a ticket purchase
    const user = await df.users.createVerified({
      email: `attendee-${Date.now()}@test.com`,
    });

    await df.ticketPurchases.create({
      userId: user.id,
      ticketTypeId: ticketType.id,
      quantity: 1,
    });

    // Generate session token for check-in (keep token helpers)
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();
    await loginAsAdmin(adminPage);
    sessionToken = await generateSessionToken(adminPage, event.id, session.id, 24);
    await adminContext.close();

    testEventId = event.id;

    // NO login - clear cookies to simulate kiosk mode
    await page.context().clearCookies();

    // Navigate with fresh token
    await navigateToCheckIn(page, testEventId, sessionToken);
    // Get attendees from API using session token (NO auth cookie)
    const attendeesData = await getAttendees(page, testEventId, sessionToken);

    // We created a test user, so attendees should exist
    expect(attendeesData).toBeTruthy();
    expect(attendeesData.attendees).toBeTruthy();
    expect(attendeesData.attendees.length).toBeGreaterThan(0);

    // Find the attendee row by email (test user won't have sceneName)
    const attendeeRow = page.locator('tr').filter({ hasText: user.email }).first();
    await expect(attendeeRow).toBeVisible({ timeout: 10000 });

    // Click "Covid Test" button first (initial state for unchecked attendees)
    // The workflow is: Covid Test → Check In → Checked In
    const covidTestButton = attendeeRow.locator('button').filter({ hasText: /covid test/i }).first();
    await expect(covidTestButton).toBeVisible({ timeout: 5000 });
    await covidTestButton.click();

    // Now "Check In" button appears
    const checkInButton = attendeeRow.locator('button').filter({ hasText: /check.?in/i }).first();
    await expect(checkInButton).toBeVisible({ timeout: 5000 });
    await checkInButton.click();

    // KIOSK MODE: Notifications are disabled for streamlined UX
    // Instead, verify the attendee shows as checked in (text changes to "✓ Checked In")
    const checkedInText = attendeeRow.locator('text=/Checked In/i').first();
    await expect(checkedInText).toBeVisible({ timeout: 5000 });
  });

  test('Cannot check in same attendee twice', async ({ page, df, browser }) => {
    // Create test data using DataFactory
    const event = await df.events.createPublished(`Check-In Duplicate Test ${Date.now()}`);

    const sessionStart = new Date();
    sessionStart.setHours(sessionStart.getHours() + 2);
    const sessionEnd = new Date(sessionStart.getTime() + 3 * 60 * 60 * 1000);

    const session = await df.sessions.create({
      eventId: event.id,
      title: 'Test Session',
      startTime: sessionStart,
      endTime: sessionEnd,
      maxCapacity: 20,
    });

    const ticketType = await df.ticketTypes.create({
      eventId: event.id,
      sessionId: session.id,
      name: 'General Admission',
      price: 0,
      quantityAvailable: 20,
    });

    // Create a user with a ticket purchase
    const user = await df.users.createVerified({
      email: `attendee-duplicate-${Date.now()}@test.com`,
    });

    await df.ticketPurchases.create({
      userId: user.id,
      ticketTypeId: ticketType.id,
      quantity: 1,
    });

    // Generate session token for check-in
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();
    await loginAsAdmin(adminPage);
    sessionToken = await generateSessionToken(adminPage, event.id, session.id, 24);
    await adminContext.close();

    testEventId = event.id;

    // NO login - clear cookies to simulate kiosk mode
    await page.context().clearCookies();

    // Navigate with fresh token
    await navigateToCheckIn(page, testEventId, sessionToken);

    // Find the attendee row by email (test user won't have sceneName)
    const attendeeRow = page.locator('tr').filter({ hasText: user.email }).first();
    await expect(attendeeRow).toBeVisible({ timeout: 10000 });

    // STEP 1: Check in the attendee (Covid Test → Check In)
    // Click "Covid Test" button first
    const covidTestButton = attendeeRow.locator('button').filter({ hasText: /covid test/i }).first();
    await expect(covidTestButton).toBeVisible({ timeout: 5000 });
    await covidTestButton.click();

    // Click "Check In" button
    const checkInButton = attendeeRow.locator('button').filter({ hasText: /check.?in/i }).first();
    await expect(checkInButton).toBeVisible({ timeout: 5000 });
    await checkInButton.click();

    // Wait for check-in to complete - "Checked In" text appears
    const checkedInText = attendeeRow.locator('text=/Checked In/i').first();
    await expect(checkedInText).toBeVisible({ timeout: 5000 });

    // STEP 2: Verify attendee CANNOT be checked in again
    // The "Covid Test" and "Check In" buttons should no longer exist
    const covidTestButtonAfter = attendeeRow.locator('button').filter({ hasText: /covid test/i });
    await expect(covidTestButtonAfter).toHaveCount(0);

    const checkInButtonAfter = attendeeRow.locator('button').filter({ hasText: /^check.?in$/i });
    await expect(checkInButtonAfter).toHaveCount(0);

    // The checked-in state shows text, not buttons - this prevents duplicate check-ins
  });

  test('Two-step check-in workflow (Covid Test → Check In)', async ({ page, df, browser }) => {
    // This test verifies the streamlined check-in workflow:
    // 1. Click "Covid Test" button (purple) - marks COVID test complete
    // 2. Click "Check In" button (green) - completes the check-in
    // No confirmation modal - direct button workflow for kiosk efficiency

    // Create test data using DataFactory
    const event = await df.events.createPublished(`Check-In Workflow Test ${Date.now()}`);

    const sessionStart = new Date();
    sessionStart.setHours(sessionStart.getHours() + 2);
    const sessionEnd = new Date(sessionStart.getTime() + 3 * 60 * 60 * 1000);

    const session = await df.sessions.create({
      eventId: event.id,
      title: 'Test Session',
      startTime: sessionStart,
      endTime: sessionEnd,
      maxCapacity: 20,
    });

    const ticketType = await df.ticketTypes.create({
      eventId: event.id,
      sessionId: session.id,
      name: 'General Admission',
      price: 0,
      quantityAvailable: 20,
    });

    // Create a user with a ticket purchase
    const user = await df.users.createVerified({
      email: `attendee-workflow-${Date.now()}@test.com`,
    });

    await df.ticketPurchases.create({
      userId: user.id,
      ticketTypeId: ticketType.id,
      quantity: 1,
    });

    // Generate session token for check-in
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();
    await loginAsAdmin(adminPage);
    sessionToken = await generateSessionToken(adminPage, event.id, session.id, 24);
    await adminContext.close();

    testEventId = event.id;

    // NO login - clear cookies to simulate kiosk mode
    await page.context().clearCookies();

    // Navigate with fresh token
    await navigateToCheckIn(page, testEventId, sessionToken);

    // Find attendee row by email (test user won't have sceneName)
    const attendeeRow = page.locator('tr').filter({ hasText: user.email }).first();
    await expect(attendeeRow).toBeVisible({ timeout: 10000 });

    // Verify the attendee email is displayed correctly
    const nameDisplay = attendeeRow.locator(`text=${user.email}`);
    await expect(nameDisplay).toBeVisible({ timeout: 3000 });

    // Step 1: Verify "Covid Test" button is visible (initial state)
    const covidTestButton = attendeeRow.locator('button').filter({ hasText: /covid test/i }).first();
    await expect(covidTestButton).toBeVisible({ timeout: 5000 });

    // Click "Covid Test" button
    await covidTestButton.click();

    // Step 2: Verify "Check In" button appears (intermediate state)
    const checkInButton = attendeeRow.locator('button').filter({ hasText: /check.?in/i }).first();
    await expect(checkInButton).toBeVisible({ timeout: 5000 });

    // Click "Check In" button to complete
    await checkInButton.click();

    // Verify final state: "Checked In" text appears (complete state)
    const checkedInText = attendeeRow.locator('text=/Checked In/i').first();
    await expect(checkedInText).toBeVisible({ timeout: 5000 });
  });

  test('Token validation fails for expired token during check-in', async ({ browser, df }) => {
    // Create test data using DataFactory
    const event = await df.events.createPublished(`Token Expiry Test ${Date.now()}`);

    const sessionStart = new Date();
    sessionStart.setHours(sessionStart.getHours() + 2);
    const sessionEnd = new Date(sessionStart.getTime() + 3 * 60 * 60 * 1000);

    const session = await df.sessions.create({
      eventId: event.id,
      title: 'Test Session',
      startTime: sessionStart,
      endTime: sessionEnd,
      maxCapacity: 20,
    });

    // Generate token with very short expiration
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();

    await loginAsAdmin(adminPage);
    const shortLivedToken = await generateSessionToken(adminPage, event.id, session.id, 0.001); // 3.6 seconds

    await adminContext.close();

    // Wait for token to expire
    await new Promise(resolve => setTimeout(resolve, 4000));

    // Try to use expired token
    const kioskContext = await browser.newContext();
    const kioskPage = await kioskContext.newPage();

    await kioskPage.context().clearCookies();

    // Navigate to a page first so page.evaluate() has a context
    await kioskPage.goto('/');

    // Try to get attendees with expired token
    // Use page.evaluate() for container compatibility
    const apiResponse = await kioskPage.evaluate(async ({ eventId, token }) => {
      const response = await fetch(`/api/checkin/events/${eventId}/attendees`, {
        headers: {
          'X-CheckIn-Token': token
        }
      });
      return { status: response.status };
    }, { eventId: event.id, token: shortLivedToken });

    // Verify 401 Unauthorized (token expired)
    expect(apiResponse.status).toBe(401);

    await kioskContext.close();
  });
});
