/**
 * Check-In System E2E Tests - Attendee Check-In Workflow
 *
 * Tests the core check-in functionality for pre-registered attendees using kiosk mode session tokens.
 * NO user authentication required - uses session tokens generated by Administrator.
 *
 * Verifies:
 * - Checking in a registered attendee
 * - Preventing duplicate check-ins
 * - Check-in modal displays correct attendee information
 * - Token validation during check-in operations
 *
 * Authentication:
 * - Uses session tokens (NO CheckInStaff login)
 * - Admin generates token in beforeAll
 * - Token sent in X-CheckIn-Token header for API calls
 * - Cookies cleared to simulate kiosk mode
 *
 * API Endpoints:
 * - POST /api/checkin/events/{eventId}/checkin (requires X-CheckIn-Token)
 * - GET /api/checkin/events/{eventId}/attendees (requires X-CheckIn-Token)
 *
 * Note: This test requires pre-registered attendees in the database.
 * If no attendees exist, some tests may be skipped gracefully.
 */

import { test, expect } from '@playwright/test';
import {
  loginAsAdmin,
  generateSessionToken,
  getTestEventId,
  navigateToCheckIn,
  getAttendees
} from './helpers/tokenHelpers';

test.describe('Check-In Attendee Workflow', () => {
  let testEventId: string;
  let sessionToken: string;

  test.beforeAll(async ({ browser }) => {
    // Admin context for token generation
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();

    await loginAsAdmin(adminPage);
    testEventId = await getTestEventId(adminPage);

    await adminContext.close();
  });

  test.beforeEach(async ({ page, browser }) => {
    // Generate fresh token for each test with extended expiration (24 hours)
    // This prevents token expiration during test execution
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();
    await loginAsAdmin(adminPage);
    sessionToken = await generateSessionToken(adminPage, testEventId, 24); // 24 hours
    await adminContext.close();

    // NO login - clear cookies to simulate kiosk mode
    await page.context().clearCookies();

    // Navigate with fresh token
    await navigateToCheckIn(page, testEventId, sessionToken);
  });

  test('Check in a registered attendee', async ({ page }) => {
    // Get attendees from API using session token (NO auth cookie)
    const attendeesData = await getAttendees(page, testEventId, sessionToken);

    // Skip test if no attendees or all are checked in
    if (!attendeesData || !attendeesData.attendees || attendeesData.attendees.length === 0) {
      test.skip(true, 'No registered attendees found for this event');
      return;
    }

    // Find an attendee who is NOT checked in
    const uncheckedAttendee = attendeesData.attendees.find(
      (a: any) => a.registrationStatus !== 'checked-in' && a.registrationStatus !== 'CheckedIn'
    );

    if (!uncheckedAttendee) {
      // All attendees are already checked in - create a test registration first
      test.skip(true, 'All attendees are already checked in - need to create test registration');
      return;
    }

    // Find the attendee row by sceneName (UI displays sceneName, not email)
    const sceneName = uncheckedAttendee.sceneName || uncheckedAttendee.email;
    const attendeeRow = page.locator('tr').filter({ hasText: sceneName }).first();
    await expect(attendeeRow).toBeVisible({ timeout: 10000 });

    // Click "Check In" button within this attendee's row
    const checkInButton = attendeeRow.locator('button').filter({ hasText: /check.?in/i }).first();
    await expect(checkInButton).toBeVisible({ timeout: 5000 });
    await checkInButton.click();

    // Verify confirmation modal appears
    const confirmationModal = page.locator('[role="dialog"], .modal, [data-testid="checkin-confirmation-modal"]');
    await expect(confirmationModal).toBeVisible({ timeout: 5000 });

    // Click "Complete Check-In" button in modal
    const confirmButton = page.locator('button').filter({ hasText: /complete.*check.*in/i }).last();
    await confirmButton.click();

    // Wait for modal to close (indicates mutation started)
    await expect(confirmationModal).not.toBeVisible({ timeout: 5000 });

    // Verify success notification appears
    // Mantine v7 creates multiple root containers (one per position), only the active one is visible
    // Look for the actual notification element with success text (will be in the visible container)
    const successNotification = page.locator('[class*="Notification"]').filter({ hasText: /success|checked/i }).first();
    await expect(successNotification).toBeVisible({ timeout: 8000 }); // Match increased autoClose time

    // Verify attendee shows as checked in
    // Look for checked-in badge or indicator
    const checkedInBadge = page.locator('text=/checked.?in/i').first();
    await expect(checkedInBadge).toBeVisible({ timeout: 5000 });

    // Verify capacity counter updates (if displayed)
    const capacityDisplay = page.locator('text=/capacity|checked.?in.*\\d+|\\d+.*checked.?in/i').first();
    if (await capacityDisplay.isVisible()) {
      // Capacity counter exists - verify it updated
      await expect(capacityDisplay).toBeVisible();
    }
  });

  test('Cannot check in same attendee twice', async ({ page }) => {
    // Get attendees from API using session token
    const attendeesData = await getAttendees(page, testEventId, sessionToken);

    // Skip test if no checked-in attendees exist
    if (!attendeesData || !attendeesData.attendees || attendeesData.attendees.length === 0) {
      test.skip(true, 'No attendees found for this event');
      return;
    }

    // Find an attendee who IS checked in
    const checkedInAttendee = attendeesData.attendees.find(
      (a: any) => a.registrationStatus === 'checked-in' || a.registrationStatus === 'CheckedIn'
    );

    if (!checkedInAttendee) {
      test.skip(true, 'No checked-in attendees found - cannot test duplicate check-in prevention');
      return;
    }

    // Find the attendee row by sceneName (UI displays sceneName, not email)
    const sceneName = checkedInAttendee.sceneName || checkedInAttendee.email;
    const attendeeRow = page.locator('tr').filter({ hasText: sceneName }).first();
    await expect(attendeeRow).toBeVisible({ timeout: 10000 });

    // Verify attendee shows as checked in (not a button, but a "✓ Checked In" text)
    const checkedInIndicator = attendeeRow.locator('text=/✓.*checked.?in/i').first();
    await expect(checkedInIndicator).toBeVisible({ timeout: 5000 });

    // Verify NO "Check In" button exists for this attendee (button is removed for checked-in attendees)
    const checkInButton = attendeeRow.locator('button').filter({ hasText: /^check.?in$/i });
    await expect(checkInButton).toHaveCount(0);
  });

  test('Check-in modal displays attendee information', async ({ page }) => {
    // Get attendees from API using session token
    const attendeesData = await getAttendees(page, testEventId, sessionToken);

    // Skip if no unchecked attendees
    if (!attendeesData || !attendeesData.attendees || attendeesData.attendees.length === 0) {
      test.skip(true, 'No attendees found for this event');
      return;
    }

    const uncheckedAttendee = attendeesData.attendees.find(
      (a: any) => a.registrationStatus !== 'checked-in' && a.registrationStatus !== 'CheckedIn'
    );

    if (!uncheckedAttendee) {
      test.skip(true, 'All attendees are already checked in');
      return;
    }

    // Find attendee row by sceneName (UI displays sceneName, not email)
    const sceneName = uncheckedAttendee.sceneName || uncheckedAttendee.email;
    const attendeeRow = page.locator('tr').filter({ hasText: sceneName }).first();
    await expect(attendeeRow).toBeVisible({ timeout: 10000 });

    // Click "Check In" button within this attendee's row
    const checkInButton = attendeeRow.locator('button').filter({ hasText: /check.?in/i }).first();
    await expect(checkInButton).toBeVisible({ timeout: 5000 });
    await checkInButton.click();

    // Wait for modal
    const modal = page.locator('[role="dialog"], .modal, [data-testid="checkin-confirmation-modal"]');
    await expect(modal).toBeVisible({ timeout: 5000 });

    // Verify modal shows attendee information
    // Scene name (email not displayed in modal - UI only shows scene name and pronouns)
    const sceneNameDisplay = modal.locator(`text=${uncheckedAttendee.sceneName || uncheckedAttendee.email}`);
    await expect(sceneNameDisplay).toBeVisible({ timeout: 3000 });

    // Pronouns (if available)
    if (uncheckedAttendee.pronouns) {
      const pronounsDisplay = modal.locator(`text=${uncheckedAttendee.pronouns}`);
      await expect(pronounsDisplay).toBeVisible({ timeout: 3000 });
    }

    // Ticket number (if available)
    if (uncheckedAttendee.ticketNumber) {
      const ticketDisplay = modal.locator(`text=${uncheckedAttendee.ticketNumber}`);
      await expect(ticketDisplay).toBeVisible({ timeout: 3000 });
    }

    // Special needs (if any)
    // This may not always be present, so we don't assert visibility

    // Waiver status - look for signed badge or waiver on file text
    const waiverBadge = modal.locator('text=/✓.*signed|waiver.*on.*file/i').first();
    if (await waiverBadge.count() > 0) {
      await expect(waiverBadge).toBeVisible();
    }

    // Close modal without confirming (test cancel functionality)
    const cancelButton = modal.locator('button').filter({ hasText: /cancel|close/i }).first();
    if (await cancelButton.count() > 0) {
      await cancelButton.click();
      await expect(modal).not.toBeVisible({ timeout: 3000 });
    }
  });

  test('Token validation fails for expired token during check-in', async ({ browser }) => {
    // Generate token with very short expiration
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();

    await loginAsAdmin(adminPage);
    const shortLivedToken = await generateSessionToken(adminPage, testEventId, 0.001); // 3.6 seconds

    await adminContext.close();

    // Wait for token to expire
    await new Promise(resolve => setTimeout(resolve, 4000));

    // Try to use expired token
    const kioskContext = await browser.newContext();
    const kioskPage = await kioskContext.newPage();

    await kioskPage.context().clearCookies();

    // Try to get attendees with expired token
    const response = await kioskPage.request.get(
      `http://localhost:5655/api/checkin/events/${testEventId}/attendees`,
      {
        headers: {
          'X-CheckIn-Token': shortLivedToken
        }
      }
    );

    // Verify 401 Unauthorized (token expired)
    expect(response.status()).toBe(401);

    await kioskContext.close();
  });
});
