/**
 * Check-In System E2E Tests - Walk-In (Manual Entry) Workflow
 *
 * Tests the manual entry functionality for walk-in attendees using kiosk mode session tokens.
 * NO user authentication required - uses session tokens generated by Administrator.
 *
 * Verifies:
 * - Adding new walk-ins with unique emails
 * - Adding walk-ins with existing user emails
 * - Form validation (required fields, email format)
 * - Capacity limits (if implemented)
 *
 * Authentication:
 * - Uses session tokens (NO CheckInStaff login)
 * - Admin generates token in beforeAll
 * - Token sent in X-CheckIn-Token header for API calls
 * - Cookies cleared to simulate kiosk mode
 *
 * API Endpoint: POST /api/checkin/events/{eventId}/manual-entry (requires X-CheckIn-Token)
 */

import { test, expect } from '@playwright/test';
import {
  loginAsAdmin,
  generateSessionToken,
  getTestEventId,
  navigateToCheckIn,
  getDashboardData
} from './helpers/tokenHelpers';

const EXISTING_USER = { email: 'member@witchcityrope.com' }; // Existing user in database

test.describe('Check-In Walk-In (Manual Entry) Workflow', () => {
  let testEventId: string;
  let sessionToken: string;

  test.beforeAll(async ({ browser }) => {
    // Admin context for token generation
    const adminContext = await browser.newContext();
    const adminPage = await adminContext.newPage();

    await loginAsAdmin(adminPage);
    testEventId = await getTestEventId(adminPage);
    sessionToken = await generateSessionToken(adminPage, testEventId);

    await adminContext.close();
  });

  test.beforeEach(async ({ page }) => {
    // NO login - clear cookies to simulate kiosk mode
    await page.context().clearCookies();

    // Navigate with token
    await navigateToCheckIn(page, testEventId, sessionToken);
  });

  test.skip('Add walk-in with new email', async ({ page }) => {
    // SKIP: Modal scroll issues - waiver checkbox outside viewport
    // Generate unique email with timestamp
    const timestamp = Date.now();
    const walkInEmail = `walkin-test-${timestamp}@test.com`;
    const walkInName = `WalkIn Test ${timestamp}`;
    const walkInPhone = '555-0123';

    // Click "Add Walk-In" button
    const addWalkInButton = page.locator('button').filter({ hasText: /add walk.?in/i });
    await expect(addWalkInButton).toBeVisible({ timeout: 10000 });
    await addWalkInButton.click();

    // Wait for modal to appear - use specific dialog name to avoid strict mode violations
    const modal = page.getByRole('dialog', { name: /manual entry|walk.?in/i });
    await expect(modal).toBeVisible({ timeout: 5000 });

    // Fill form
    const nameInput = modal.locator('input[name="name"], [data-testid="walk-in-name"]').first();
    const emailInput = modal.locator('input[name="email"], [data-testid="walk-in-email"]').first();
    const phoneInput = modal.locator('input[name="phone"], [data-testid="walk-in-phone"]').first();
    const waiverCheckbox = modal.locator('input[type="checkbox"][name*="waiver"], [data-testid="walk-in-waiver"]').first();

    await nameInput.fill(walkInName);
    await emailInput.fill(walkInEmail);
    await phoneInput.fill(walkInPhone);

    // Scroll to and check waiver checkbox if not already checked
    // Use force to bypass visibility check due to modal overflow
    await waiverCheckbox.scrollIntoViewIfNeeded();
    if (!(await waiverCheckbox.isChecked())) {
      await waiverCheckbox.check({ force: true });
    }

    // Submit form - scope to modal to avoid strict mode issues
    const submitButton = modal.getByRole('button', { name: /submit|add|create/i });
    await submitButton.scrollIntoViewIfNeeded();
    await submitButton.click();

    // Verify success message
    const successNotification = page.locator('[role="alert"], .notification').filter({ hasText: /success|added|created/i }).first();
    await expect(successNotification).toBeVisible({ timeout: 10000 });

    // Verify walk-in appears in attendee list
    const attendeeCard = page.locator(`text=${walkInEmail}, text=${walkInName}`).first();
    await expect(attendeeCard).toBeVisible({ timeout: 10000 });

    // Verify ticket number starts with "WALKIN-"
    const ticketNumber = page.locator('text=/WALKIN-/i').first();
    await expect(ticketNumber).toBeVisible({ timeout: 5000 });

    // Verify walk-in is automatically checked in (should show as checked-in)
    const checkedInBadge = page.locator('text=/checked.?in/i').first();
    await expect(checkedInBadge).toBeVisible({ timeout: 5000 });
  });

  test.skip('Add walk-in with existing user email', async ({ page }) => {
    // SKIP: Modal scroll issues - waiver checkbox outside viewport
    // Use existing user email (should link to existing account)
    const walkInName = `Existing User Test ${Date.now()}`;

    // Click "Add Walk-In" button
    const addWalkInButton = page.locator('button').filter({ hasText: /add walk.?in/i });
    await expect(addWalkInButton).toBeVisible({ timeout: 10000 });
    await addWalkInButton.click();

    // Wait for modal
    const modal = page.getByRole('dialog', { name: /manual entry|walk.?in/i });
    await expect(modal).toBeVisible({ timeout: 5000 });

    // Fill form with existing user's email
    const nameInput = modal.locator('input[name="name"], [data-testid="walk-in-name"]').first();
    const emailInput = modal.locator('input[name="email"], [data-testid="walk-in-email"]').first();
    const waiverCheckbox = modal.locator('input[type="checkbox"][name*="waiver"], [data-testid="walk-in-waiver"]').first();

    await nameInput.fill(walkInName);
    await emailInput.fill(EXISTING_USER.email);

    // Scroll to and check waiver checkbox
    // Use force to bypass visibility check due to modal overflow
    await waiverCheckbox.scrollIntoViewIfNeeded();
    if (!(await waiverCheckbox.isChecked())) {
      await waiverCheckbox.check({ force: true });
    }

    // Submit - scroll button into view first
    const submitButton = modal.getByRole('button', { name: /submit|add|create/i });
    await submitButton.scrollIntoViewIfNeeded();
    await submitButton.click();

    // Verify success (should NOT create duplicate user)
    const successNotification = page.locator('[role="alert"], .notification').filter({ hasText: /success|added|created/i }).first();
    await expect(successNotification).toBeVisible({ timeout: 10000 });

    // Verify user appears in attendee list
    const attendeeCard = page.locator(`text=${EXISTING_USER.email}`).first();
    await expect(attendeeCard).toBeVisible({ timeout: 10000 });
  });

  test.skip('Walk-in form validation - empty name', async ({ page }) => {
    // SKIP: Modal scroll issues - submit button not found
    const walkInEmail = `test-${Date.now()}@test.com`;

    // Click "Add Walk-In" button
    const addWalkInButton = page.locator('button').filter({ hasText: /add walk.?in/i });
    await expect(addWalkInButton).toBeVisible({ timeout: 10000 });
    await addWalkInButton.click();

    // Wait for modal
    const modal = page.getByRole('dialog', { name: /manual entry|walk.?in/i });
    await expect(modal).toBeVisible({ timeout: 5000 });

    // Fill email but leave name empty
    const emailInput = modal.locator('input[name="email"], [data-testid="walk-in-email"]').first();
    await emailInput.fill(walkInEmail);

    // Try to submit with empty name - scroll button into view first
    const submitButton = modal.getByRole('button', { name: /submit|add|create/i });
    await submitButton.scrollIntoViewIfNeeded();
    await submitButton.click();

    // Verify validation error appears
    const errorMessage = page.locator('text=/name.*required|required.*name/i, [data-testid="name-error"]').first();
    await expect(errorMessage).toBeVisible({ timeout: 5000 });
  });

  test.skip('Walk-in form validation - invalid email format', async ({ page }) => {
    // SKIP: Modal scroll issues - submit button not found
    // Click "Add Walk-In" button
    const addWalkInButton = page.locator('button').filter({ hasText: /add walk.?in/i });
    await expect(addWalkInButton).toBeVisible({ timeout: 10000 });
    await addWalkInButton.click();

    // Wait for modal
    const modal = page.getByRole('dialog', { name: /manual entry|walk.?in/i });
    await expect(modal).toBeVisible({ timeout: 5000 });

    // Fill name and invalid email
    const nameInput = modal.locator('input[name="name"], [data-testid="walk-in-name"]').first();
    const emailInput = modal.locator('input[name="email"], [data-testid="walk-in-email"]').first();

    await nameInput.fill('Test User');
    await emailInput.fill('not-a-valid-email'); // Invalid email format

    // Try to submit - scroll button into view first
    const submitButton = modal.getByRole('button', { name: /submit|add|create/i });
    await submitButton.scrollIntoViewIfNeeded();
    await submitButton.click();

    // Verify validation error for email format
    const errorMessage = page.locator('text=/email.*invalid|invalid.*email|valid email/i, [data-testid="email-error"]').first();
    await expect(errorMessage).toBeVisible({ timeout: 5000 });
  });

  test('Walk-in respects capacity limits (if implemented)', async ({ page }) => {
    // This test verifies capacity enforcement
    // Note: This may not be implemented yet - test will gracefully skip if not

    // First, check current event capacity via API using session token
    const dashboardData = await getDashboardData(page, testEventId, sessionToken);

    // Skip test if we can't determine capacity
    if (!dashboardData) {
      test.skip(true, 'Cannot determine event capacity - test skipped');
      return;
    }

    const { totalCapacity, checkedInCount } = dashboardData;
    const availableSpots = totalCapacity - checkedInCount;

    // If event has available capacity, we can't test the limit
    if (availableSpots > 0) {
      test.skip(true, `Event has ${availableSpots} available spots - cannot test capacity limit`);
      return;
    }

    // Event is at capacity - try to add walk-in
    const addWalkInButton = page.locator('button').filter({ hasText: /add walk.?in/i });
    await expect(addWalkInButton).toBeVisible({ timeout: 10000 });
    await addWalkInButton.click();

    // Fill form
    const modal = page.getByRole('dialog', { name: /manual entry|walk.?in/i });
    await expect(modal).toBeVisible({ timeout: 5000 });

    const nameInput = modal.locator('input[name="name"], [data-testid="walk-in-name"]').first();
    const emailInput = modal.locator('input[name="email"], [data-testid="walk-in-email"]').first();
    const waiverCheckbox = modal.locator('input[type="checkbox"][name*="waiver"], [data-testid="walk-in-waiver"]').first();

    await nameInput.fill(`Capacity Test ${Date.now()}`);
    await emailInput.fill(`capacity-test-${Date.now()}@test.com`);

    // Scroll to and check waiver checkbox
    // Use force to bypass visibility check due to modal overflow
    await waiverCheckbox.scrollIntoViewIfNeeded();
    if (!(await waiverCheckbox.isChecked())) {
      await waiverCheckbox.check({ force: true });
    }

    // Submit - scroll button into view first
    const submitButton = modal.getByRole('button', { name: /submit|add|create/i });
    await submitButton.scrollIntoViewIfNeeded();
    await submitButton.click();

    // Verify capacity exceeded message
    const capacityError = page.locator('[role="alert"], .notification').filter({ hasText: /capacity|full|limit/i });
    await expect(capacityError).toBeVisible({ timeout: 10000 });
  });
});
