using System.ComponentModel.DataAnnotations;

namespace WitchCityRope.Api.Features.CheckIn.Entities;

/// <summary>
/// Session token for kiosk mode check-in access
/// Tokens are generated by admins and allow check-in operations without user authentication
///
/// CRITICAL: This is NOT user authentication - tokens provide scoped access to specific events
/// Pattern: Admin generates token → Opens on kiosk device → Volunteers use without login
/// </summary>
public class CheckInSessionToken
{
    /// <summary>
    /// Unique identifier for the session token
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Cryptographically secure token string (64 characters, URL-safe base64)
    /// Used in URLs and API headers for kiosk authentication
    /// </summary>
    [Required]
    [MaxLength(64)]
    public string Token { get; set; } = string.Empty;

    /// <summary>
    /// Event this token grants access to
    /// Tokens are scoped to a single event for security
    /// </summary>
    public Guid EventId { get; set; }

    /// <summary>
    /// Specific session this token grants check-in access to (backwards compatibility)
    /// NULLABLE for multi-session token support
    /// For single-session tokens, this field is populated
    /// For multi-session tokens, use TokenSessions collection instead
    /// </summary>
    public Guid? SessionId { get; set; }

    /// <summary>
    /// Admin user who generated this token
    /// Used for audit trail and security investigation
    /// </summary>
    public Guid CreatedByUserId { get; set; }

    /// <summary>
    /// When the token was generated (UTC)
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// When the token expires (default: 12 hours after creation)
    /// After expiration, token is automatically invalid
    /// </summary>
    public DateTime ExpiresAt { get; set; }

    /// <summary>
    /// Whether the token has been manually revoked by an admin
    /// Used for emergency revocation if device is lost/compromised
    /// </summary>
    public bool IsRevoked { get; set; }

    /// <summary>
    /// When the token was revoked (if applicable)
    /// </summary>
    public DateTime? RevokedAt { get; set; }

    /// <summary>
    /// Admin user who revoked this token (if applicable)
    /// </summary>
    public Guid? RevokedByUserId { get; set; }

    /// <summary>
    /// Last time this token was used for a check-in operation
    /// Updated on every check-in API call for monitoring
    /// </summary>
    public DateTime? LastUsedAt { get; set; }

    // Navigation properties
    public WitchCityRope.Api.Models.Event? Event { get; set; }
    public WitchCityRope.Api.Models.Session? Session { get; set; }

    /// <summary>
    /// Sessions this token grants access to (multi-session support)
    /// For modern multi-session tokens, this collection is populated
    /// For backwards compatibility single-session tokens, SessionId is used
    /// </summary>
    public ICollection<CheckInSessionTokenSession> TokenSessions { get; set; } = new List<CheckInSessionTokenSession>();

    /// <summary>
    /// Constructor initializes required fields
    /// </summary>
    public CheckInSessionToken()
    {
        Id = Guid.NewGuid();
        CreatedAt = DateTime.UtcNow;
        IsRevoked = false;
    }
}
