version: '3.8'

# Development overrides
services:
  api:
    build:
      context: ../
      dockerfile: src/WitchCityRope.Api/Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Logging__LogLevel__Default=Debug
      - Logging__LogLevel__Microsoft=Information
      - Logging__LogLevel__Microsoft.Hosting.Lifetime=Information
    volumes:
      - ../src/WitchCityRope.Api:/app/src/WitchCityRope.Api
      - ../src/WitchCityRope.Core:/app/src/WitchCityRope.Core
      - ../src/WitchCityRope.Infrastructure:/app/src/WitchCityRope.Infrastructure
      - api-dev-data:/app/data
    ports:
      - "5653:8080"
      - "5050:5050"  # For debugging
    command: ["dotnet", "watch", "run", "--no-launch-profile"]

  web:
    build:
      context: ../
      dockerfile: src/WitchCityRope.Web/Dockerfile.dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ApiSettings__BaseUrl=http://api:8080
      - Logging__LogLevel__Default=Debug
    volumes:
      - ../src/WitchCityRope.Web:/app/src/WitchCityRope.Web
      - ../src/WitchCityRope.Core:/app/src/WitchCityRope.Core
    ports:
      - "5651:8080"
      - "5051:5051"  # For debugging
    command: ["dotnet", "watch", "run", "--no-launch-profile"]

  # Development database UI (optional)
  adminer:
    image: adminer:latest
    container_name: witchcityrope-adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=sqlite
    networks:
      - witchcityrope-network
    profiles:
      - debug

  # Development mail server (optional)
  mailhog:
    image: mailhog/mailhog:latest
    container_name: witchcityrope-mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - witchcityrope-network
    profiles:
      - debug

volumes:
  api-dev-data:
    name: witchcityrope-api-dev-data