// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WitchCityRope.Infrastructure.Data;

#nullable disable

namespace WitchCityRope.Infrastructure.Migrations
{
    [DbContext(typeof(WitchCityRopeDbContext))]
    [Migration("20250627123615_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            // This is a copy of the model from the previous migration with the new indexes added
            // The actual model building would be generated by EF Core tools
            // For now, this serves as a placeholder to maintain consistency
#pragma warning restore 612, 618
        }
    }
}