import type { components } from '@witchcityrope/shared-types';
import { apiClient } from '../../../lib/api/client';

/**
 * Autogenerated types from backend C# DTOs
 * Source of truth: backend API schemas
 */
export type SessionTokenResponse = components['schemas']['SessionTokenResponse'];
export type GenerateTokenRequest = components['schemas']['GenerateTokenRequest'];
export type RevokeTokenRequest = components['schemas']['RevokeTokenRequest'];

const API_BASE = '/api/checkin/session-tokens';

/**
 * API client for check-in session token management
 *
 * Session tokens enable kiosk mode check-in access without requiring
 * staff members to log in on shared devices. Tokens are event-specific
 * and time-limited for security.
 *
 * All endpoints require Administrator or EventOrganizer role.
 * Uses apiClient for consistent error handling and CSRF protection.
 */
export const sessionTokenApi = {
  /**
   * Generate a new check-in session token (Admin/EventOrganizer only)
   *
   * @param request - Event ID and optional expiration time
   * @returns Session token response with check-in URL
   */
  async generateToken(request: GenerateTokenRequest): Promise<SessionTokenResponse> {
    const response = await apiClient.post(`${API_BASE}/generate`, request);
    return response.data;
  },

  /**
   * Revoke an existing token (Admin/EventOrganizer only)
   *
   * @param request - Token to revoke
   */
  async revokeToken(request: RevokeTokenRequest): Promise<void> {
    await apiClient.post(`${API_BASE}/revoke`, request);
  },

  /**
   * List active tokens for an event (Admin/EventOrganizer only)
   *
   * @param eventId - Event ID to list tokens for
   * @returns Array of active session tokens
   */
  async listActiveTokens(eventId: string): Promise<SessionTokenResponse[]> {
    const response = await apiClient.get(`${API_BASE}/event/${eventId}`);
    return response.data;
  },
};
