import type { components } from '@witchcityrope/shared-types';

/**
 * Autogenerated types from backend C# DTOs
 * Source of truth: backend API schemas
 */
export type SessionTokenResponse = components['schemas']['SessionTokenResponse'];
export type GenerateTokenRequest = components['schemas']['GenerateTokenRequest'];
export type RevokeTokenRequest = components['schemas']['RevokeTokenRequest'];

const API_BASE = '/api/checkin/session-tokens';

/**
 * API client for check-in session token management
 *
 * Session tokens enable kiosk mode check-in access without requiring
 * staff members to log in on shared devices. Tokens are event-specific
 * and time-limited for security.
 *
 * All endpoints require Administrator or EventOrganizer role.
 */
export const sessionTokenApi = {
  /**
   * Generate a new check-in session token (Admin/EventOrganizer only)
   *
   * @param request - Event ID and optional expiration time
   * @returns Session token response with check-in URL
   * @throws Error with specific message for 401 (not authenticated), 403 (insufficient permissions), or other failures
   */
  async generateToken(request: GenerateTokenRequest): Promise<SessionTokenResponse> {
    const response = await fetch(`${API_BASE}/generate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include', // Admin auth cookie
      body: JSON.stringify(request),
    });

    if (!response.ok) {
      if (response.status === 401) throw new Error('Not authenticated. Please log in.');
      if (response.status === 403) throw new Error('Insufficient permissions. Admin or EventOrganizer role required.');

      // Try to extract error message from response
      try {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to generate check-in token');
      } catch {
        throw new Error('Failed to generate check-in token');
      }
    }

    return response.json();
  },

  /**
   * Revoke an existing token (Admin/EventOrganizer only)
   *
   * @param request - Token to revoke
   * @throws Error with specific message for auth or permission failures
   */
  async revokeToken(request: RevokeTokenRequest): Promise<void> {
    const response = await fetch(`${API_BASE}/revoke`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify(request),
    });

    if (!response.ok) {
      if (response.status === 401) throw new Error('Not authenticated. Please log in.');
      if (response.status === 403) throw new Error('Insufficient permissions. Admin or EventOrganizer role required.');

      try {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to revoke token');
      } catch {
        throw new Error('Failed to revoke token');
      }
    }
  },

  /**
   * List active tokens for an event (Admin/EventOrganizer only)
   *
   * @param eventId - Event ID to list tokens for
   * @returns Array of active session tokens
   * @throws Error with specific message for auth or permission failures
   */
  async listActiveTokens(eventId: string): Promise<SessionTokenResponse[]> {
    const response = await fetch(`${API_BASE}/event/${eventId}`, {
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
    });

    if (!response.ok) {
      if (response.status === 401) throw new Error('Not authenticated. Please log in.');
      if (response.status === 403) throw new Error('Insufficient permissions. Admin or EventOrganizer role required.');

      try {
        const errorData = await response.json();
        throw new Error(errorData.message || 'Failed to list active tokens');
      } catch {
        throw new Error('Failed to list active tokens');
      }
    }

    return response.json();
  },
};
