name: Build and Push Docker Images

on:
  # Manual trigger only - no automatic builds on push
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag (latest, staging, or commit SHA)'
        required: false
        default: 'latest'
      environment:
        description: 'Target environment (production or staging)'
        required: true
        type: choice
        options:
          - staging
          - production
        default: 'staging'

env:
  DOCKER_REGISTRY: registry.digitalocean.com/witchcityrope

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: set-tag
        run: |
          # Use manual input values
          echo "IMAGE_TAG=${{ github.event.inputs.image_tag || 'latest' }}" >> $GITHUB_ENV
          echo "ENVIRONMENT=${{ github.event.inputs.environment || 'staging' }}" >> $GITHUB_ENV
          echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # =======================================================================
      # Build and Push API Image
      # =======================================================================
      - name: Build API Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/witchcityrope-api:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_REGISTRY }}/witchcityrope-api:${{ env.SHORT_SHA }}
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/witchcityrope-api:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/witchcityrope-api:buildcache,mode=max
          target: production

      # =======================================================================
      # Build and Push Web Image
      # =======================================================================
      - name: Build Web Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/witchcityrope-web:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_REGISTRY }}/witchcityrope-web:${{ env.SHORT_SHA }}
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/witchcityrope-web:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/witchcityrope-web:buildcache,mode=max
          target: production
          build-args: |
            VITE_API_BASE_URL=
            VITE_APP_TITLE=WitchCityRope
            VITE_APP_VERSION=${{ env.SHORT_SHA }}

      # =======================================================================
      # Summary and Notifications
      # =======================================================================
      - name: Build Summary
        run: |
          echo "## Docker Images Built and Pushed :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Environment:** ${{ env.ENVIRONMENT }}" >> $GITHUB_STEP_SUMMARY
          echo "**Image Tag:** ${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit SHA:** ${{ env.SHORT_SHA }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Images:" >> $GITHUB_STEP_SUMMARY
          echo "- API: \`${{ env.DOCKER_REGISTRY }}/witchcityrope-api:${{ env.IMAGE_TAG }}\`" >> $GITHUB_STEP_SUMMARY
          echo "- Web: \`${{ env.DOCKER_REGISTRY }}/witchcityrope-web:${{ env.IMAGE_TAG }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ env.ENVIRONMENT }}" == "staging" ]; then
            echo "**Next Step:** Manually deploy to staging via Actions → Deploy to Staging" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ env.ENVIRONMENT }}" == "production" ]; then
            echo "**Next Step:** Manually deploy to production via Actions → Deploy to Production" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Notify deployment ready
        run: |
          echo "✅ Docker images built and pushed successfully"
          echo ""
          echo "Images ready in registry:"
          echo "  - witchcityrope-api:${{ env.IMAGE_TAG }}"
          echo "  - witchcityrope-web:${{ env.IMAGE_TAG }}"
          echo ""
          echo "To deploy to ${{ env.ENVIRONMENT }}:"
          echo "  1. Go to Actions tab"
          echo "  2. Select 'Deploy to ${{ env.ENVIRONMENT == 'staging' && 'Staging' || 'Production' }}' workflow"
          echo "  3. Click 'Run workflow'"
          echo "  4. Use image tag: ${{ env.IMAGE_TAG }}"
          if [ "${{ env.ENVIRONMENT }}" == "production" ]; then
            echo "  5. Type 'DEPLOY' to confirm"
          fi
