name: Playwright JavaScript Tests

on:
  push:
    branches: [ main, develop, feature/playwright-migration ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test-suite:
        description: 'Test suite to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - auth
          - events
          - admin
          - validation

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: WitchCity2024!
          POSTGRES_DB: witchcityrope_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps chromium firefox webkit

    - name: Build application
      run: |
        dotnet build src/WitchCityRope.Web/WitchCityRope.Web.csproj

    - name: Start application
      run: |
        dotnet run --project src/WitchCityRope.Web/WitchCityRope.Web.csproj &
        echo "Waiting for application to start..."
        npx wait-on http://localhost:5651 --timeout 60000

    - name: Run Playwright tests
      run: |
        if [ "${{ github.event.inputs.test-suite }}" = "all" ] || [ -z "${{ github.event.inputs.test-suite }}" ]; then
          npx playwright test
        else
          npx playwright test tests/playwright/${{ github.event.inputs.test-suite }}
        fi
      env:
        BASE_URL: http://localhost:5651
        CI: true
        DATABASE_URL: postgresql://postgres:WitchCity2024!@localhost:5432/witchcityrope_test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload test videos
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-videos
        path: test-results/
        retention-days: 7