name: Nightly Playwright Tests

on:
  schedule:
    # Run at 2 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      test-suite:
        description: 'Test suite to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - auth
          - events
          - admin
          - rsvp
          - validation

jobs:
  nightly-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: WitchCity2024!
          POSTGRES_DB: witchcityrope_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npx playwright install --with-deps chromium firefox webkit

    - name: Build application
      run: |
        dotnet build src/WitchCityRope.Web/WitchCityRope.Web.csproj

    - name: Start application
      run: |
        dotnet run --project src/WitchCityRope.Web/WitchCityRope.Web.csproj &
        echo "Waiting for application to start..."
        npx wait-on http://localhost:5651 --timeout 60000

    - name: Run Playwright tests
      run: |
        if [ "${{ github.event.inputs.test-suite }}" = "all" ] || [ -z "${{ github.event.inputs.test-suite }}" ]; then
          npx playwright test --reporter=html,github,junit
        else
          npx playwright test tests/playwright/${{ github.event.inputs.test-suite }} --reporter=html,github,junit
        fi
      env:
        BASE_URL: http://localhost:5651
        CI: true
        DATABASE_URL: postgresql://postgres:WitchCity2024!@localhost:5432/witchcityrope_test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ github.run_id }}
        path: playwright-report/
        retention-days: 30

    - name: Upload test videos
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-videos-${{ github.run_id }}
        path: test-results/
        retention-days: 7

    - name: Send Slack notification on failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: 'Nightly Playwright tests failed! Check the results.'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Create issue on failure
      if: failure()
      uses: actions/create-issue@v2
      with:
        title: 'Nightly Playwright Tests Failed - ${{ github.run_id }}'
        body: |
          The nightly Playwright test run has failed.
          
          **Run ID**: ${{ github.run_id }}
          **Test Suite**: ${{ github.event.inputs.test-suite || 'all' }}
          **Time**: ${{ github.event.repository.updated_at }}
          
          [View Test Results](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          
          Please investigate and fix the failing tests.
        labels: 'bug,test-failure,playwright'